#!/usr/bin/env bash
# Zai installer with always-fresh guarantee.
# Builds from source and puts `zai` on PATH.
#
# Default install layout in PREFIX (default ~/.local/bin):
#   zai.bin  real release binary
#   zai      wrapper that rebuilds when sources are newer, then execs zai.bin
# That wrapper is what makes every `zai ...` run use the latest source build.
#
# Usage:
#   ./install.sh
#   ./install.sh --debug
#   ./install.sh --prefix DIR
#   ./install.sh --force
#   ./install.sh --check
#   ./install.sh --yes
#   ./install.sh --no-wrapper
#   zai update [--check] [--force] [--yes]
#
# Env:
#   ZAI_NO_AUTO_UPDATE=1  skip auto rebuild for one run
#   ZAI_UPDATE_VERBOSE=1  print rebuild notes from the wrapper
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="release"
PREFIX="${HOME:-/root}/.local/bin"
SYSTEM_DIR="/usr/local/bin"
FORCE=0
CHECK=0
ASSUME_YES=0
USE_WRAPPER=1

usage() {
  cat <<'HELP'
Usage: ./install.sh [options]
       zai update [options]

Options:
  --debug        build debug profile, faster, larger binary
  --release      build release profile (default)
  --prefix DIR   install binaries into DIR (default: ~/.local/bin)
  --force        rebuild and reinstall even if already fresh
  --check        only check freshness, exit 0 when fresh, 1 when stale
  --yes          non-interactive, assume yes for prompts
  --no-wrapper   install raw binary as `zai`, disable auto update wrapper
  --help         show this help

Auto update:
  The installed `zai` is a wrapper. On each run it checks whether any file
  under crates/, Cargo.toml, or Cargo.lock is newer than the installed
  binary. When stale it rebuilds once (single-flight lock) and then runs.
  Run `zai update` to force an update, `zai update --check` to inspect.
  Set ZAI_NO_AUTO_UPDATE=1 to skip the check for one run.

After install, open a new shell or export PATH, then run: zai doctor
HELP
}

while [ $# -gt 0 ]; do
  case "$1" in
    --debug) MODE="debug"; shift ;;
    --release) MODE="release"; shift ;;
    --prefix) PREFIX="${2:?missing DIR}"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --check) CHECK=1; shift ;;
    --yes) ASSUME_YES=1; shift ;;
    --no-wrapper) USE_WRAPPER=0; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

log() { echo "zai: $*"; }
warn() { echo "zai: $*" >&2; }

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: $1 not found. $2" >&2
    exit 2
  fi
}

source_version() {
  sed -n 's/^version *= *"\([^"]*\)".*/\1/p' "$REPO_DIR/crates/cli/Cargo.toml" | head -n 1
}

installed_version() {
  local bin="$1"
  if [ -x "$bin" ]; then
    "$bin" --version 2>/dev/null | awk '{print $2}' || true
  fi
}

real_target() {
  if [ "$USE_WRAPPER" = "1" ]; then
    echo "$PREFIX/zai.bin"
  else
    echo "$PREFIX/zai"
  fi
}

build_bin() {
  if [ "$MODE" = "release" ]; then
    echo "$REPO_DIR/target/release/zai"
  else
    echo "$REPO_DIR/target/debug/zai"
  fi
}

is_fresh() {
  local dest
  dest="$(real_target)"
  if [ ! -x "$dest" ]; then
    return 1
  fi
  local src_ver inst_ver
  src_ver="$(source_version)"
  inst_ver="$(installed_version "$dest")"
  if [ -n "$src_ver" ] && [ -n "$inst_ver" ] && [ "$src_ver" != "$inst_ver" ]; then
    return 1
  fi
  if [ "$USE_WRAPPER" = "1" ] && [ ! -f "$PREFIX/zai" ]; then
    return 1
  fi
  # Stale when any tracked source is newer than the installed binary.
  if command -v find >/dev/null 2>&1; then
    if find "$REPO_DIR/crates" "$REPO_DIR/Cargo.toml" "$REPO_DIR/Cargo.lock" \
      -type f -newer "$dest" -print -quit 2>/dev/null | grep -q .; then
      return 1
    fi
  fi
  return 0
}

write_wrapper() {
  local wrapper="$PREFIX/zai"
  local tmp="$wrapper.tmp.$$"
  cat > "$tmp" <<EOF
#!/usr/bin/env bash
# Generated by $REPO_DIR/install.sh. Do not edit by hand.
# Wrapper keeps zai fresh: rebuilds when sources are newer, then execs zai.bin.
set -uo pipefail
REPO_DIR="$REPO_DIR"
INSTALL_SH="\$REPO_DIR/install.sh"
REAL_BIN="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)/zai.bin"

if [ "\${1:-}" = "update" ] || [ "\${1:-}" = "self-update" ]; then
  shift || true
  if [ ! -x "\$INSTALL_SH" ]; then
    echo "zai: updater not found at \$INSTALL_SH" >&2
    exit 1
  fi
  exec bash "\$INSTALL_SH" "\$@"
fi

ARGS=()
SKIP=0
for a in "\$@"; do
  if [ "\$a" = "--no-auto-update" ]; then
    SKIP=1
  else
    ARGS+=("\$a")
  fi
done
if [ "\${ZAI_NO_AUTO_UPDATE:-0}" = "1" ]; then
  SKIP=1
fi
if [ "\$SKIP" = "1" ]; then
  exec "\$REAL_BIN" "\${ARGS[@]:-}"
fi
if [ ! -d "\$REPO_DIR" ] || [ ! -f "\$REPO_DIR/Cargo.toml" ]; then
  exec "\$REAL_BIN" "\${ARGS[@]:-}"
fi
if [ ! -x "\$REAL_BIN" ]; then
  bash "\$INSTALL_SH" --yes >/dev/null 2>&1 || true
  exec "\$REAL_BIN" "\${ARGS[@]:-}"
fi
if command -v find >/dev/null 2>&1; then
  if find "\$REPO_DIR/crates" "\$REPO_DIR/Cargo.toml" "\$REPO_DIR/Cargo.lock" \
    -type f -newer "\$REAL_BIN" -print -quit 2>/dev/null | grep -q .; then
    LOCK="/tmp/zai-build.lock"
    if mkdir "\$LOCK" 2>/dev/null; then
      trap 'rmdir "\$LOCK" 2>/dev/null || true' EXIT
      if [ "\${ZAI_UPDATE_VERBOSE:-0}" = "1" ]; then
        echo "zai: sources changed, rebuilding..." >&2
      fi
      if bash "\$INSTALL_SH" --yes >/dev/null 2>&1; then
        if [ "\${ZAI_UPDATE_VERBOSE:-0}" = "1" ]; then
          echo "zai: updated" >&2
        fi
      else
        echo "zai: auto update failed, running installed build" >&2
      fi
      rmdir "\$LOCK" 2>/dev/null || true
      trap - EXIT
    fi
  fi
fi
exec "\$REAL_BIN" "\${ARGS[@]:-}"
EOF
  chmod +x "$tmp"
  mv -f "$tmp" "$wrapper"
}

SRC_VER="$(source_version)"
if [ "$CHECK" = "1" ]; then
  if [ "$FORCE" = "1" ]; then
    echo "zai: check with --force always reports stale" >&2
    exit 1
  fi
  if is_fresh; then
    log "up to date (v${SRC_VER:-unknown}) at $(real_target)"
    exit 0
  else
    log "update available (source v${SRC_VER:-unknown}), run: ./install.sh or zai update"
    exit 1
  fi
fi

need_cmd cargo "Install Rust stable first: https://rustup.rs"

if is_fresh && [ "$FORCE" = "0" ]; then
  log "up to date (v${SRC_VER:-unknown}) at $(real_target), use --force to rebuild"
  if [ "$USE_WRAPPER" = "1" ] && [ ! -f "$PREFIX/zai" ]; then
    mkdir -p "$PREFIX"
    write_wrapper
    log "wrapper restored at $PREFIX/zai"
  fi
  exit 0
fi

if [ "$ASSUME_YES" = "0" ] && [ -t 0 ]; then
  log "building ($MODE profile) from $REPO_DIR..."
fi

if [ "$MODE" = "release" ]; then
  (cd "$REPO_DIR" && cargo build --locked --release -p zai)
  BIN="$REPO_DIR/target/release/zai"
else
  (cd "$REPO_DIR" && cargo build -p zai)
  BIN="$REPO_DIR/target/debug/zai"
fi

if [ ! -x "$BIN" ]; then
  echo "error: build produced no binary at $BIN" >&2
  exit 1
fi

mkdir -p "$PREFIX"
DEST="$(real_target)"
if [ -f "$DEST" ]; then
  cp -f "$DEST" "$DEST.old" 2>/dev/null || true
fi
cp -f "$BIN" "$DEST"
chmod +x "$DEST"
log "installed to $DEST"

if [ "$USE_WRAPPER" = "1" ]; then
  write_wrapper
  log "wrapper installed at $PREFIX/zai (auto rebuild on stale sources)"
  # Remove stale raw install confusion: keep zai.old backup from previous layout.
  if [ -f "$PREFIX/zai.old" ] && [ ! -f "$PREFIX/zai.bin.old" ]; then
    mv -f "$PREFIX/zai.old" "$PREFIX/zai.bin.old" 2>/dev/null || true
  fi
else
  # Raw mode: ensure no stale wrapper shadows the binary.
  if [ -f "$PREFIX/zai.bin" ] && [ "$DEST" = "$PREFIX/zai" ]; then
    rm -f "$PREFIX/zai.bin" 2>/dev/null || true
  fi
fi

# Offer system wide install when possible, never required.
install_system() {
  local src="$1"
  local name="$2"
  if [ "$PREFIX" = "$SYSTEM_DIR" ]; then
    return 0
  fi
  if [ -w "$SYSTEM_DIR" ]; then
    cp -f "$src" "$SYSTEM_DIR/$name" && chmod +x "$SYSTEM_DIR/$name" && log "also installed to $SYSTEM_DIR/$name"
  elif command -v sudo >/dev/null 2>&1; then
    if sudo cp -f "$src" "$SYSTEM_DIR/$name" 2>/dev/null; then
      sudo chmod +x "$SYSTEM_DIR/$name"
      log "also installed to $SYSTEM_DIR/$name"
    fi
  fi
}

if [ "$USE_WRAPPER" = "1" ]; then
  install_system "$DEST" "zai.bin"
  install_system "$PREFIX/zai" "zai"
else
  install_system "$DEST" "zai"
fi

case ":$PATH:" in
  *":$PREFIX:"*) PATH_OK=1 ;;
  *) PATH_OK=0 ;;
esac
if [ "$PATH_OK" -eq 0 ]; then
  echo "note: $PREFIX is not on PATH. Add this line to ~/.bashrc or ~/.zshrc:"
  echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo "then open a new shell."
fi

log "verifying install..."
if command -v zai >/dev/null 2>&1; then
  ZAI_NO_AUTO_UPDATE=1 zai doctor
else
  ZAI_NO_AUTO_UPDATE=1 "$DEST" doctor
fi
log "done. Update anytime with: zai update (or ./install.sh --force)"
log "Check freshness with: zai update --check"
