#!/usr/bin/env bash
# Zai installer. No options: every run builds the latest release from
# source and installs it, so the installed binary is always fresh.
#
# Installed layout in ~/.local/bin (plus /usr/local/bin when writable):
#   zai.bin  real release binary
#   zai      wrapper that rebuilds when sources are newer, then execs zai.bin
#
# Usage:
#   ./install.sh
#   zai update
#
# Env:
#   ZAI_NO_AUTO_UPDATE=1  skip the wrapper auto rebuild for one run
#   ZAI_UPDATE_VERBOSE=1  print rebuild notes from the wrapper
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${HOME:-/root}/.local/bin"
SYSTEM_DIR="/usr/local/bin"

log() { echo "zai: $*"; }

if ! command -v cargo >/dev/null 2>&1; then
  echo "error: cargo not found. Install Rust stable first: https://rustup.rs" >&2
  exit 2
fi

log "building release from $REPO_DIR..."
# Robust build: default target first, fallback to a temp target when the
# repo target is polluted by root-owned files (old sudo builds).
if ! (cd "$REPO_DIR" && cargo build --locked --release -p zai); then
  log "default target failed, retrying with temp target..."
  FALLBACK_DIR="${TMPDIR:-/tmp}/zai-build-$USER"
  mkdir -p "$FALLBACK_DIR"
  (cd "$REPO_DIR" && CARGO_TARGET_DIR="$FALLBACK_DIR" cargo build --locked --release -p zai)
  BIN="$FALLBACK_DIR/release/zai"
else
  BIN="$REPO_DIR/target/release/zai"
fi
if [ ! -x "$BIN" ]; then
  echo "error: build produced no binary at $BIN" >&2
  echo "hint: sudo chown -R \$USER \"$REPO_DIR/target\" then rerun ./install.sh" >&2
  exit 1
fi

mkdir -p "$PREFIX"
DEST="$PREFIX/zai.bin"
if [ -f "$DEST" ]; then
  cp -f "$DEST" "$DEST.old" 2>/dev/null || true
fi
cp -f "$BIN" "$DEST"
chmod +x "$DEST"
log "installed to $DEST"

# Wrapper: keeps every `zai ...` run on the latest source build.
WRAPPER="$PREFIX/zai"
TMP="$WRAPPER.tmp.$$"
cat > "$TMP" <<EOF
#!/usr/bin/env bash
# Generated by $REPO_DIR/install.sh. Do not edit by hand.
# Wrapper keeps zai fresh: rebuilds when sources are newer, then execs zai.bin.
set -uo pipefail
REPO_DIR="$REPO_DIR"
INSTALL_SH="\$REPO_DIR/install.sh"
REAL_BIN="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)/zai.bin"

if [ "\${1:-}" = "update" ] || [ "\${1:-}" = "self-update" ]; then
  if [ "\${2:-}" = "--check" ]; then
    if [ ! -x "\$REAL_BIN" ]; then
      echo "zai: no installed binary, run: ./install.sh" >&2
      exit 1
    fi
    if command -v find >/dev/null 2>&1; then
      if find "\$REPO_DIR/crates" "\$REPO_DIR/Cargo.toml" "\$REPO_DIR/Cargo.lock" "\$REPO_DIR/install.sh" \
        -type f -newer "\$REAL_BIN" -print -quit 2>/dev/null | grep -q .; then
        echo "zai: update available, run: zai update"
        exit 1
      fi
    fi
    echo "zai: up to date"
    exit 0
  fi
  if [ ! -x "\$INSTALL_SH" ]; then
    echo "zai: updater not found at \$INSTALL_SH" >&2
    exit 1
  fi
  exec bash "\$INSTALL_SH"
fi

ARGS=()
SKIP=0
for a in "\$@"; do
  if [ "\$a" = "--no-auto-update" ]; then
    SKIP=1
  else
    ARGS+=("\$a")
  fi
done
if [ "\${ZAI_NO_AUTO_UPDATE:-0}" = "1" ]; then
  SKIP=1
fi
if [ "\$SKIP" = "1" ]; then
  exec -a zai "\$REAL_BIN" "\${ARGS[@]:-}"
fi
if [ ! -d "\$REPO_DIR" ] || [ ! -f "\$REPO_DIR/Cargo.toml" ]; then
  exec -a zai "\$REAL_BIN" "\${ARGS[@]:-}"
fi
if [ ! -x "\$REAL_BIN" ]; then
  ZAI_NO_AUTO_UPDATE=1 bash "\$INSTALL_SH" >/dev/null 2>&1 || true
  exec -a zai "\$REAL_BIN" "\${ARGS[@]:-}"
fi
if command -v find >/dev/null 2>&1; then
  if find "\$REPO_DIR/crates" "\$REPO_DIR/Cargo.toml" "\$REPO_DIR/Cargo.lock" "\$REPO_DIR/install.sh" \
    -type f -newer "\$REAL_BIN" -print -quit 2>/dev/null | grep -q .; then
    LOCK="/tmp/zai-build.lock"
    if mkdir "\$LOCK" 2>/dev/null; then
      trap 'rmdir "\$LOCK" 2>/dev/null || true' EXIT
      if [ "\${ZAI_UPDATE_VERBOSE:-0}" = "1" ]; then
        echo "zai: sources changed, rebuilding..." >&2
      fi
      if ZAI_NO_AUTO_UPDATE=1 bash "\$INSTALL_SH" >/dev/null 2>&1; then
        if [ "\${ZAI_UPDATE_VERBOSE:-0}" = "1" ]; then
          echo "zai: updated" >&2
        fi
      else
        echo "zai: auto update failed, running installed build" >&2
      fi
      rmdir "\$LOCK" 2>/dev/null || true
      trap - EXIT
    fi
  fi
fi
exec -a zai "\$REAL_BIN" "\${ARGS[@]:-}"
EOF
chmod +x "$TMP"
mv -f "$TMP" "$WRAPPER"
log "wrapper installed at $WRAPPER (auto rebuild on stale sources)"

# Offer system wide install when possible, never required.
if [ "$PREFIX" != "$SYSTEM_DIR" ]; then
  if [ -w "$SYSTEM_DIR" ]; then
    cp -f "$DEST" "$SYSTEM_DIR/zai.bin" && chmod +x "$SYSTEM_DIR/zai.bin" && log "also installed to $SYSTEM_DIR/zai.bin"
    cp -f "$WRAPPER" "$SYSTEM_DIR/zai" && chmod +x "$SYSTEM_DIR/zai" && log "also installed to $SYSTEM_DIR/zai"
  elif command -v sudo >/dev/null 2>&1; then
    if sudo cp -f "$DEST" "$SYSTEM_DIR/zai.bin" 2>/dev/null; then
      sudo chmod +x "$SYSTEM_DIR/zai.bin"
      sudo cp -f "$WRAPPER" "$SYSTEM_DIR/zai" 2>/dev/null || true
      sudo chmod +x "$SYSTEM_DIR/zai" 2>/dev/null || true
      log "also installed to $SYSTEM_DIR/zai"
    fi
  fi
fi

case ":$PATH:" in
  *":$PREFIX:"*) ;;
  *)
    echo "note: $PREFIX is not on PATH. Add this line to ~/.bashrc or ~/.zshrc:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo "then open a new shell."
    ;;
esac

log "verifying install..."
ZAI_NO_AUTO_UPDATE=1 "$DEST" doctor
log "done. Update anytime with: zai update"
